### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by jbesraa** [foundersandcoders/Live-Peers#1]
discuss about the repo name.

if you have anything to add or to edit, please share it.

**Comment by jsms90** [comment]
(Feel free to edit this comment)

Ideas were:
+ live-peers
+ community-live
+ peer-to-peer
+ participate-live
+ live-campus

**Comment by jsms90** [comment]
Went with `live-peers` as it communicates the two things we want from this project:
+ communication in real time = "live"
+ facilitate the sharing of knowledge among equals = `peers`
