### ISSUE TITLE
Button showing number of students & moderators online

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/Live-Peers#19]
+ Different coloured circles to represent the different roles (student & moderator)
+ Numbers next to the relevant circle, which update in real-time
+ Numbers flash whenever a new person joins/leaves the room (?)

**Comment by nogainbar** [comment]
In terms of the design, I am not sure this would be the best solution, i would suggest talking about this before you start building it.

**Comment by nogainbar** [comment]
also, is this a button or just a display? is it the same as issue #20?
